### ISSUE TITLE
Local timezone does not work with daylight savings

### ISSUE THREAD

**Issue by alexcepoi** [enkore/i3pystatus#352] opened 2016-03-30 12:59 UTC
I think https://github.com/enkore/i3pystatus/commit/e31c58f1ade860dc497b424aff7bc971928249a6 breaks daylight savings support.

time.tzname returns ('GMT', 'BST') for me. Currently i3pystatus will always display the 'GMT' version as localtime which is incorrect.

**Comment by richese** [comment] 2016-03-30 17:25
My time is shown correctly and I did not notice any problems when _dst_ changed few days ago.

Can I ask you to post:
* what settings you use when registering `clock`
* output of `timedatectl` (if you use systemd)
* what is `/etc/localtime` symlinked to (or its last line if it isn't a symlink)

**Comment by terminalmage** [comment] 2016-03-30 19:45
@alexcepoi See https://github.com/enkore/i3pystatus/pull/347, I noticed the same and found and fixed it here. Still awaiting merge though.

**Comment by terminalmage** [comment] 2016-03-30 19:49
Also, @alexcepoi, I'd be thrilled if you could test this. I only confirmed that it worked on my own laptop, and that it should work in principle for a few international timezones that I tested, but I haven't tested with my own localtime set to GMT.

**Comment by terminalmage** [comment] 2016-03-30 20:30
It looks like my fix should work for you:

```python
>>> # My local timezone is US/Central
...
>>> time.tzname
('CST', 'CDT')
>>> os.environ.putenv('TZ', 'Europe/London')
>>> time.tzset()
>>> time.tzname
('GMT', 'BST')
>>> clock = i3pystatus.clock.Clock()
>>> clock._get_local_tz()
'GMT+00:00BST'
>>> # Set back to my local TZ
...
>>> os.environ.putenv('TZ', 'US/Central')
>>> time.tzset()
>>> time.tzname
('CST', 'CDT')
>>> # Use the programatically-derived TZ value
...
>>> os.environ.putenv('TZ', 'GMT+00:00BST')
>>> time.tzset()
>>> time.tzname
('GMT', 'BST')
```

**Comment by alexcepoi** [comment] 2016-03-30 22:33
Thanks for looking into this guys.

Configuration:
does not work: format='%a %-d %b %H:%M'
this works: format=('%a %-d %b %H:%M', 'Europe/London')

$ cat /etc/localtime | tail -n 1
GMT0BST,M3.5.0/1,M10.5.0

$ timedatectl
      Local time: Wed 2016-03-30 23:21:04 BST
  Universal time: Wed 2016-03-30 22:21:04 UTC
        RTC time: Wed 2016-03-30 22:21:04
        Timezone: Europe/London (BST, +0100)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: yes
 Last DST change: DST began at
                  Sun 2016-03-27 00:59:59 GMT
                  Sun 2016-03-27 02:00:00 BST
 Next DST change: DST ends (the clock jumps one hour backwards) at
                  Sun 2016-10-30 01:59:59 BST
                  Sun 2016-10-30 01:00:00 GMT

@terminalmage I have no $TZ set. Tried your change, seems to be outputting the time in PDT, which is definitely not my local time.

**Comment by terminalmage** [comment] 2016-03-31 04:01
@alexcepoi I have no TZ set either. The TZ value is irrelevant here, it is not sourced at any point. It is simply set based on values derived from `time.tzname`.

Here's my configuration:

```
TIME_FORMAT = '%a, %b %d %Y, %H:%M:%S %Z'

status.register(
    'clock',
    format=[
        TIME_FORMAT,
        (TIME_FORMAT, 'US/Mountain'),
        (TIME_FORMAT, 'US/Pacific'),
    ],
)
```

When I set my timezone to `Europe/London` (using `timedatectl set-timezone Europe/London`), the clock module updates immediately (no reload required), and shows the correct timezone (BST). It is set back to BST properly when I scroll through the other timezones and return to the one without an explicit timezone set.

May I ask what you did to test?

**Comment by alexcepoi** [comment] 2016-04-12 16:33
Sorry for the delay in replying. I see the PR got merged. Here is how I tested this:
https://gist.githubusercontent.com/alexcepoi/837d4a0dfc54e216f2a443c5bf3955e0/raw/fa7d8e1c954a278b77a53fec618b87148b068e16/gistfile1.txt

It still does not work properly for me, as you can see  HEAD currently reports in the west coast by default (I have no idea why).

**Comment by terminalmage** [comment] 2016-05-18 19:06
I'm sorry, but none of that gist makes any sense to me. I'm running from HEAD right now and it works just fine for me.

**Comment by enkore** [comment] 2016-07-14 16:22
@alexcepoi do you still experience the problem or is this fixed?

**Comment by alexcepoi** [comment] 2016-07-16 11:42
I am hardcoding the timezone in order to get past the issue.

I tried again on HEAD, but still have the same problem. If someone is still looking into this, it seems it cannot find my timezone and assumes local timezone to be whatever last timezone was requested:

https://gist.github.com/alexcepoi/2e62e6622f4204eab99027eda813e911

**Comment by terminalmage** [comment] 2016-07-16 17:36
So you have more than one clock module registered?

**Comment by alexcepoi** [comment] 2016-07-16 18:19
Yeah

**Comment by terminalmage** [comment] 2016-07-18 13:02
I'm not sure that's intended to be supported behavior. Running ``time.tzset()`` changes the timezone for the i3pystatus process. This is why the "local" timezone (i.e. the timezone used when one is not explicitly defined) for the 2nd instance of the clock module is the same as the most-recently-set one for the first module.

**Comment by alexcepoi** [comment] 2016-07-18 15:17
Ah, that makes sense. I personally think it's silly to use tzset() then for determining the correct time for another timezone (if no cleanup is performed).

status.register(
    'clock',
    format=[
        TIME_FORMAT,
        (TIME_FORMAT, 'US/Mountain'),
        (TIME_FORMAT, 'US/Pacific'),
    ],
)

In your example here, wouldn't the same problem occur if you move TIME_FORMAT after (TIME_FORMAT, 'US/Mountain')?

The reason I am using another instance of clock is because I want different colors for different timezones.

**Comment by facetoe** [comment] 2016-07-20 11:11
@alexcepoi you might be able to set the different colours using Pango hints instead of running multiple clock instances - https://i3pystatus.readthedocs.io/en/latest/configuration.html#hints.

**Comment by facetoe** [comment] 2016-08-10 13:01
#410 reintroduced the `pytz` dependancy and should have fixed this issue, do you still have this problem with the latest code @alexcepoi?

**Comment by alexcepoi** [comment] 2016-09-08 18:11
Sorry for the delay. Just tested this from head and can confirm it's working again for me.

Thanks.

**Comment by lasers** [comment] 2019-03-24 01:35
Can somebody close this issue?

**Closed** 2019-03-24 06:47 UTC
